name: Sanaya_user
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.13
  skeletons: ^0.0.3
  carousel_slider: ^4.1.1
  get: ^4.6.5
  country_code_picker: ^2.0.2
  otp_text_field: ^1.1.3
  google_maps_flutter: ^2.1.5
  flutter_switch: ^0.3.2
  image_picker: ^0.8.5+3
  geolocator: ^8.2.1
  url_launcher: ^6.1.4
  flutter_share: ^2.0.0
  date_picker_timeline: ^1.2.3
  jiffy: ^5.0.0
  connectivity_plus: ^2.3.5
  flutter_multi_formatter: ^2.5.7
  webview_flutter: ^3.0.4
  geocoding: ^2.0.4
  google_nav_bar: ^5.0.6
  flutter_html: ^3.0.0-alpha.5
  flutter_otp_text_field: ^1.1.1

  change_app_package_name: ^1.1.0
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  badges: ^3.0.2
  rename:
  rename_app: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sliders/
    - assets/images/

  fonts:
    - family: bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: semibold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf

    - family: medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
